[logger]
level = "INFO"
path = "./logs/logfile.log"

# TODO
# ...
[storage]
type = "sql"
dsn = "user=calendar_user password=123456 dbname=calendar sslmode=disable"

[server]
host="localhost"
port="4500"