[logger]
level = "INFO"
path = "./logs/logfile.log"

[storage]
type = "memory"
dsn = "user=calendar_user password=123456 dbname=calendar sslmode=disable"

[http]
host="localhost"
port="4500"

[grpc]
host="localhost"
port="4501"